version: "3.8"

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "26000:26000"
    networks:
      - app_network
    depends_on:
      - postgres
      - minio
      - redis
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_BUCKET_NAME: desafio-processo-seletivo-seplag-bucket
      STORAGE_ACCESS_KEY: user
      STORAGE_SECRET_KEY: 12345678

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=desafio-processo-seletivo-seplag-db
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_db:/volumes/data/postgres
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: "12345678"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_store:/data
    networks:
        - app_network

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
          /bin/sh -c "
          sleep 5 &&
          mc alias set local http://minio:9000 user 12345678 &&
          mc mb local/miniobucket &&
          mc anonymous set download local/miniobucket &&
          exit 0;
          "
    networks:
      - app_network

  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis_db:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  minio_store:
    driver: local
  postgres_db:
    driver: local
  redis_db:
    driver: local